from .controller import Controller
from .ref import Reference as _ref

# Buttons
A = _ref.A
B = _ref.B
X = _ref.X
Y = _ref.Y
Z = _ref.Z
L = _ref.L
R = _ref.R
JOYSTICK = _ref.JOYSTICK
CSTICK = _ref.CSTICK
START = _ref.START
# Joystick States
JOYSTICK_NORTH = _ref.JOYSTICK_NORTH
JOYSTICK_NORTH_EAST = _ref.JOYSTICK_NORTH_EAST
JOYSTICK_EAST = _ref.JOYSTICK_EAST
JOYSTICK_SOUTH_EAST = _ref.JOYSTICK_SOUTH_EAST
JOYSTICK_SOUTH = _ref.JOYSTICK_SOUTH
JOYSTICK_SOUTH_WEST = _ref.JOYSTICK_SOUTH_WEST
JOYSTICK_WEST = _ref.JOYSTICK_WEST
JOYSTICK_NORTH_WEST = _ref.JOYSTICK_NORTH_WEST
# Joystick Extensions
JOYSTICK_FULL_EXTENSION = _ref.JOYSTICK_FULL_EXTENSION
JOYSTICK_HALF_EXTENSION = _ref.JOYSTICK_HALF_EXTENSION
